export const buildingData = [
  {
    id: 1,
    price: 7500000,
    beds: 4,
    baths: 4.5,
    area: 350.0,
    location:
      "Idu after the train station junction. Opposite Broad View Estate Idu., Abuja",
    property_type: "semi detached duplex",
  },
  {
    id: 2,
    price: 12000000,
    beds: 6,
    baths: 6.5,
    area: 600.0,
    location:
      "Idu after the train station junction. Opposite Broad View Estate Idu., Abuja",
    property_type: "",
  },
  {
    id: 3,
    price: 10500000,
    beds: 4,
    baths: 4.5,
    area: 500.0,
    location:
      "Idu after the train station junction. Opposite Broad View Estate Idu., Abuja",
    property_type: "",
  },
  {
    id: 4,
    price: 4000000,
    beds: 2,
    baths: 2.5,
    area: 180.0,
    location: "Abuja",
    property_type: "2-bedroom-terrace-duplex",
  },
  {
    id: 5,
    price: 5500000,
    beds: 4,
    baths: 4.5,
    area: 250.0,
    location: "Abuja",
    property_type: "Cornerpiece",
  },
  {
    id: 6,
    price: 2500000,
    beds: 4,
    baths: 4.5,
    area: 250.0,
    location: "Abuja",
    property_type: "Cornerpiece",
  },
  {
    id: 7,
    price: 2500000,
    beds: 2,
    baths: 2.5,
    area: 180.0,
    location: "Abuja",
    property_type: "2-bedroom-terrace-duplex",
  },
  {
    id: 8,
    price: 3000000,
    beds: 4,
    baths: 4.5,
    area: 250.0,
    location: "Abuja",
    property_type: "",
  },
  {
    id: 9,
    price: 5500000,
    beds: 4,
    baths: 4.5,
    area: 500.0,
    location:
      "Behind Valington Phase 4, Behind Mantrac by Aco Estate Airport Road, Abuja",
    property_type: "",
  },
  {
    id: 10,
    price: 7500000,
    beds: 6,
    baths: 6.5,
    area: 600.0,
    location: "Abuja",
    property_type: "",
  },
  {
    id: 11,
    price: 6500000,
    beds: 4,
    baths: 4.5,
    area: 500.0,
    location: "Abuja",
    property_type: "",
  },
  {
    id: 12,
    price: 5000000,
    beds: 4,
    baths: 4.5,
    area: 350.0,
    location: "Abuja",
    property_type: "semi detached duplex",
  },
  {
    id: 13,
    price: 4000000,
    beds: 4,
    baths: 4.5,
    area: 250.0,
    location: "Abuja",
    property_type: "",
  },
  {
    id: 14,
    price: 3000000,
    beds: 2,
    baths: 2.5,
    area: 180.0,
    location: "Abuja",
    property_type: "2-bedroom-terrace-duplex",
  },
  {
    id: 15,
    price: 6500000,
    beds: 6,
    baths: 7,
    area: 600.0,
    location:
      "Idu After the Train Station, Sharing Fence with NIMC Estate, Abuja",
    property_type: "",
  },
  {
    id: 16,
    price: 5000000,
    beds: 4,
    baths: 5,
    area: 350.0,
    location:
      "Idu After the Train Station, Sharing Fence with NIMC Estate, Abuja",
    property_type: "semi detached duplex",
  },
  {
    id: 17,
    price: 3500000,
    beds: 3,
    baths: 3,
    area: 180.0,
    location:
      "Idu Train Station Junction, Sharing Fence with Valington Premium City Cluster 2, Abuja",
    property_type: "2-bedroom-terrace-duplex",
  },
  {
    id: 18,
    price: 24000000,
    beds: 18,
    baths: 24,
    area: 1000.0,
    location:
      "Behind Dunamis Glory Dome, Sharing Fence With RiverPark Estate Lugbe Abuja",
    property_type: "6 units of 3 Bedroom Blocks of flat",
  },
  {
    id: 19,
    price: 10000000,
    beds: 5,
    baths: 5.5,
    area: 600.0,
    location:
      "Behind Dunamis Glory Dome, Sharing Fence With RiverPark Estate Lugbe Abuja",
    property_type: "4-BEDROOM-PENTHOUSE",
  },
  {
    id: 20,
    price: 6000000,
    beds: 4,
    baths: 6,
    area: 250.0,
    location:
      "Behind Dunamis Glory Dome, Sharing Fence With RiverPark Estate Lugbe Abuja",
    property_type: "4 bedroom terrace duplex",
  },
  {
    id: 21,
    price: 12000000,
    beds: 6,
    baths: 6.5,
    area: 700.0,
    location:
      "Behind Dunamis Glory Dome, Sharing Fence With RiverPark Estate Lugbe Abuja",
    property_type: "5 bedroom Duplex Valington",
  },
  {
    id: 22,
    price: 7000000,
    beds: 4,
    baths: 4.5,
    area: 500.0,
    location: "Behind Mantrack by Aco Estate Lugbe Abuja",
    property_type: "5 bedroom duplex",
  },
  {
    id: 23,
    price: 5000000,
    beds: 4,
    baths: 4.5,
    area: 350.0,
    location: "Behind Mantrack by Aco Estate Lugbe Abuja",
    property_type: "semi detached duplex",
  },
  {
    id: 24,
    price: 4000000,
    beds: 4,
    baths: 4.5,
    area: 250.0,
    location: "Behind Mantrack by Aco Estate Lugbe Abuja",
    property_type: "Terrace Duplexes",
  },
  {
    id: 25,
    price: 3000000,
    beds: 4,
    baths: 4.5,
    area: 250.0,
    location:
      "Behind Valington Phase 4. Behind Mantrack by Aco Estate Lugbe Abuja",
    property_type: "Terrace Duplexes",
  },
  {
    id: 26,
    price: 6500000,
    beds: 4,
    baths: 4.5,
    area: 500.0,
    location:
      "Behind AP filling station Kpeyegi, Opposite Anglican Comprehensive Secondary School, Jikwoyi FCT Abuja",
    property_type: "valington",
  },
  {
    id: 27,
    price: 5500000,
    beds: 3,
    baths: 3.5,
    area: 400.0,
    location:
      "By AP filling station Kpeyegi, Opposite Ave-Maria College, Jikwoyi FCT Abuja",
    property_type: "",
  },
  {
    id: 28,
    price: 4500000,
    beds: 3,
    baths: 3.5,
    area: 350.0,
    location:
      "Behind AP filling station Kpeyegi, Opposite Anglican Comprehensive Secondary School, Jikwoyi FCT Abuja",
    property_type: "Semi Detached Bungalow",
  },
  {
    id: 29,
    price: 2500000,
    beds: 2,
    baths: 2.5,
    area: 200.0,
    location:
      "Behind AP filling station Kpeyegi, Opposite Anglican Comprehensive Secondary School, Jikwoyi FCT Abuja",
    property_type: "Semi Detached Bungalow",
  },
  {
    id: 30,
    price: 6000000,
    beds: 5,
    baths: 5.5,
    area: 500.0,
    location:
      "By AP filling station Kpeyegi, Opposite Ave-Maria College, Jikwoyi FCT Abuja",
    property_type: "",
  },
];
